[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 500
evm_version = "paris"
fs_permissions = [{ access = "read", path = "./"}]
ffi = false
remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
  "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
  "erc6551/=lib/reference/src/"
]

[fmt]
line_length = 100

[profile.ci]
# keep runs modest for speed; deterministic seed
fuzz_runs = 256
invariant_runs = 256
invariant_depth = 128
invariant_fail_on_revert = false
seed = "0xDEADBEEF"    # any fixed seed

# Optional: exclude heavy test dirs from coverage
coverage = true