name: Slither
on: [pull_request]

jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: crytic/slither-action@v0.4.0
        with:
          target: "."
          fail-on: "high,medium"
          slither-args: "--exclude-unused-return"