name: Solidity CI
on: [push, pull_request]

jobs:
  forge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: foundry-rs/foundry-toolchain@v1
        with: { version: nightly }
      - name: Install Slither and lcov
        run: |
          pip install slither-analyzer
          sudo apt-get update && sudo apt-get install -y lcov
      - name: Build
        run: forge build --sizes
      - name: Test
        run: forge test --fuzz-seed 0xDEADBEEF --fuzz-runs 256 -vvv
        env:
          FOUNDRY_INVARIANT_RUNS: 256
      - name: Coverage gate
        run: |
          forge coverage --report lcov
          if [ $(lcov --summary lcov.info | grep -oP 'lines\.\.\.\.\.\.: \K\d+\.\d+') < 60 ]; then
            echo "Coverage is below 60%"
            exit 1
          fi
      - name: Run Slither
        run: slither . --fail-high --fail-medium